apiVersion: v1
kind: Service
metadata: 
  name: user-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   '/metrics'
    prometheus.io/port:   '3001'
spec: 
  selector: 
    app: user-service
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: NodePort